services:
  - type: web
    name: jeevitham-website
    env: node
    buildCommand: |
      npm config set package-manager npm@10.2.4
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    nodeVersion: 18.x 