services:
  - type: static
    name: jeevitham-website
    env: node
    buildCommand: |
      npm config set package-manager npm@10.2.4
      npm install
      npm run build
    staticPublishPath: .next
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable 