services:
  - type: web
    name: jeevitham-website
    env: node
    buildCommand: |
      rm -f pnpm-lock.yaml
      rm -f yarn.lock
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    nodeVersion: 18.x 