services:
  - type: web
    name: jeevitham-website
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    healthCheckPath: /
    autoDeploy: true
    nodeVersion: 18.x 